export const reactProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "/assets/projects/monsters-rolodex/video.mp4",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
  {
    id: 2,
    title: "Google Clone with ReactJS",
    description: "It's a google clone with ReactJS. I'ts a functional component based app. I've used Context API for state management and I've used Custom Search JSON API of Google and it's so much easy to use.",
    language: "Javascript",
    dependecies: ["react-router-dom", "material-ui/core", "material-ui/icons"],
    platform: "Web",
    images: ["/assets/projects/google-clone/1.png", "/assets/projects/google-clone/2.png", "/assets/projects/google-clone/3.png",],
    coverImg: "/assets/projects/google-clone/4.png",
    videoUrl: "",
    liveUrl: "https://google-clone86664.netlify.app/",
    sourceCodeUrl: "https://github.com/tahmid86664/google-clone",
  },
  {
    id: 3,
    title: "Fire Chat with ReactJS, Firebase and ChatEngine.IO",
    description: "It's a realtime chat app. I've used firebase for storage, database and for google authentication. I've also implemented facebook authentication. The main thing is the ChatEngine.IO. It's a great and powerful API.",
    language: "Javascript",
    dependecies: ["react-router-dom", "firebase", "axios", "react-chat-engine(ChatEngine.IO)"],
    platform: "Web",
    images: ["/assets/projects/fire-chat/2.png", "/assets/projects/fire-chat/3.png", "/assets/projects/fire-chat/4.png", "/assets/projects/fire-chat/5.png", "/assets/projects/fire-chat/6.png",],
    coverImg: "/assets/projects/fire-chat/1.png",
    videoUrl: "",
    liveUrl: "https://firechat86664.netlify.app/",
    sourceCodeUrl: "https://github.com/tahmid86664/fire-chat",
  },
  {
    id: 4,
    title: "Instagram Clone with ReactJS and Firebase",
    description: "It's a Instragram clone with ReactJS and Firebase. Firebase is used for storage, database and email authentication. It's a simple and clean post sharing app. You can add post or comment after signing in.",
    language: "Javascript",
    dependecies: ["firebase", "react-emoji"],
    platform: "Web",
    images: ["/assets/projects/instagram-clone/1.png", "/assets/projects/instagram-clone/2.png", "/assets/projects/instagram-clone/3.png", "/assets/projects/instagram-clone/4.png",],
    coverImg: "/assets/projects/instagram-clone/cover.png",
    videoUrl: "",
    liveUrl: "https://instagram-clone86664.netlify.app/",
    sourceCodeUrl: "https://github.com/tahmid86664/instagram-clone",
  },
  {
    id: 5,
    title: "Friendlyyy, a Social App using ReactJS and SASS",
    description: "It's a social media app using React with dynamic data which are not from database. These are mock data. You can login with different users, here 10 users are available for testing. You can like and dislike posts. You can see birthday of someone which dynamic and realtime. Also users have profile page which also dynamic using mock data. Online friends bar also dynamic. For styling I've used SASS. It's clean and simple. You can also visit the register and login page which are designed but not functional. Links: https://friendlyyy-react.netlify.app/login, https://friendlyyy-react.netlify.app/register. This app is fully funtional in MERN stack build, go to MERN Stack tab and see with full functionality.",
    language: "Javascript",
    dependecies: ["node-sass", "react-emoji", "react-router-dom", "query-string"],
    platform: "Web",
    images: ["/assets/projects/friendlyyy-react/1.png", "/assets/projects/friendlyyy-react/2.png", "/assets/projects/friendlyyy-react/3.png"],
    coverImg: "/assets/projects/friendlyyy-react/1.png",
    videoUrl: "",
    liveUrl: "https://friendlyyy-react.netlify.app/",
    sourceCodeUrl: "https://github.com/tahmid86664/social-media-react",
  },
];

export const javascriptProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
];

export const nodeProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
];

export const mernProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
];

export const javaProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
];

export const cProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
];

export const csharpProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
];

export const aspProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
];

export const gameProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
];

export const featuredProjects = [
  {
    id: 1,
    title: "Monsters Rolodex with ReactJS",
    description: "It's my first React project having class based components. It's a simple project containing some monsters cards having nice transition effect and a functional search bar. You can search or filter monsters from the search bar.",
    language: "Javascript",
    dependecies: [],
    platform: "Web",
    images: ["/assets/projects/monsters-rolodex/1.png", "/assets/projects/monsters-rolodex/2.png", "/assets/projects/monsters-rolodex/3.png"],
    coverImg: "/assets/projects/monsters-rolodex/1.png",
    videoUrl: "",
    liveUrl: "https://tahmid86664.github.io/monsters-rolodex/",
    sourceCodeUrl: "https://github.com/tahmid86664/monsters-rolodex-code",
  },
  {
    id: 2,
    title: "",
    description: "",
    language: "",
    dependecies: [],
    environment: "",
    platform: "",
    images: [],
    coverImg: "",
    videoUrl: "",
    liveUrl: "",
    sourceCodeUrl: "",
  },
  {
    id: 3,
    title: "",
    description: "",
    language: "",
    dependecies: [],
    environment: "",
    platform: "",
    images: [],
    coverImg: "",
    videoUrl: "",
    liveUrl: "",
    sourceCodeUrl: "",
  },
]