export const javaScriptProject = [
  {
    id: 1,
    title: "",
    description: "",
    language: "",
    dependecies: [],
    environment: "",
    platform: "",
    images: [],
    coverImg: "",
    videoUrl: "",
    liveUrl: "",
    sourceCodeUrl: "",
  },
  {
    id: 2,
    title: "",
    description: "",
    language: "",
    dependecies: [],
    environment: "",
    platform: "",
    images: [],
    coverImg: "",
    videoUrl: "",
    liveUrl: "",
    sourceCodeUrl: "",
  },
  {
    id: 3,
    title: "",
    description: "",
    language: "",
    dependecies: [],
    environment: "",
    platform: "",
    images: [],
    coverImg: "",
    videoUrl: "",
    liveUrl: "",
    sourceCodeUrl: "",
  },
]